import { defineToolcraft } from "@/toolcraft/runtime";

import { appIdentity } from "./app-identity";
import { INTERACTION_DEMO_ACTION } from "./robot-head/interaction-demo";

export const appSchema = defineToolcraft({
  canvas: {
    enabled: true,
    renderScale: true,
    size: { height: 900, unit: "px", width: 1400 },
    sizing: { mode: "editable-output" },
    upload: false,
  },
  identity: appIdentity,
  panels: {
    controls: {
      sections: [
        {
          id: "source",
          title: "URDF 模型包",
          controls: {
            variant: {
              applicability: { mode: "always" },
              defaultValue: "head1",
              keyframeable: false,
              label: "内置模型",
              options: [{ label: "Head 1", value: "head1" }, { label: "Head 2", value: "head2" }, { label: "Head 3", value: "head3" }],
              orderRole: "mode",
              performanceReason: "切换预置机械结构并重新绑定三轴关节。",
              performanceRole: "responsiveness",
              target: "model.variant",
              type: "select",
            },
            folder: {
              applicability: { mode: "conditional", all: [{ oneOf: ["head1", "head2"], target: "model.variant" }] },
              defaultValue: { fileCount: 7, kind: "bundled", name: "head" },
              description: "选择包含 URDF 与其 meshes 等依赖文件的完整文件夹。",
              keyframeable: false,
              label: "模型文件夹",
              orderRole: "input",
              performanceReason: "选择文件夹会重新解析 URDF 并上传网格到保留的 Three.js 场景。",
              performanceRole: "responsiveness",
              target: "source.urdfFolder",
              type: "urdfFolder",
            },
          },
        },
        {
          id: "motion",
          title: "三自由度动作",
          controls: {
            demoIntensity: {
              applicability: { mode: "always" },
              defaultValue: 1,
              description: "统一缩放整段动作的幅度，调整后点击生成。模型、旋转中心和角度限位沿用当前设置。",
              keyframeable: false,
              label: "表现幅度",
              min: 0.5,
              max: 1.2,
              step: 0.05,
              sliderValueKind: "continuous",
              orderRole: "primary",
              performanceRole: "responsiveness",
              performanceReason: "生成时统一缩放固定数量的三轴关键帧。",
              target: "motion.demoIntensity",
              type: "slider",
            },
            demo: {
              applicability: { mode: "always" },
              actions: [{ label: "生成完整演示", value: INTERACTION_DEMO_ACTION }],
              defaultValue: null,
              description: "替换当前时间轴并连续播放 60 秒：招呼、抬头低头、左右查看、跟随、好奇、疑惑、聆听、确认、摇头、说话、委屈、恢复和开心。播放后使用顶部时间轴重播或暂停。",
              keyframeable: false,
              label: "60 秒连续互动",
              orderRole: "action",
              target: "motion.demo",
              type: "actions",
            },
            tracking: {
              defaultValue: { enabled: false, smoothing: 0.7 },
              description: "使用摄像头实时捕捉人头姿态，或把动作采样到现有三轴时间轴。",
              keyframeable: false,
              label: "人头姿态捕捉",
              orderRole: "input",
              performanceReason: "浏览器端 MediaPipe 检测更新保留的三个 URDF 关节。",
              performanceRole: "responsiveness",
              target: "capture.headTracking",
              type: "headTracking",
            },
            pitch: {
              defaultValue: 0,
              label: "Pitch / axis1",
              max: 0.61,
              min: -0.61,
              orderRole: "primary",
              performanceReason: "只更新 axis1 的保留关节变换。",
              performanceRole: "responsiveness",
              step: 0.01,
              target: "motion.pitch",
              type: "slider",
              unit: "rad",
            },
            roll: {
              defaultValue: 0,
              label: "Roll / axis2",
              max: 0.52,
              min: -0.52,
              orderRole: "primary",
              performanceReason: "只更新 axis2 的保留关节变换。",
              performanceRole: "responsiveness",
              step: 0.01,
              target: "motion.roll",
              type: "slider",
              unit: "rad",
            },
            yaw: {
              defaultValue: 0,
              label: "Yaw / axis3",
              max: 1.65,
              min: -1.65,
              orderRole: "primary",
              performanceReason: "只更新 axis3 的保留关节变换。",
              performanceRole: "responsiveness",
              step: 0.01,
              target: "motion.yaw",
              type: "slider",
              unit: "rad",
            },
          },
        },
        {
          id: "robot",
          title: "机器人参数",
          controls: {
            scale: {
              defaultValue: 1,
              keyframeable: true,
              label: "整体比例",
              max: 1.6,
              min: 0.5,
              orderRole: "detail",
              performanceReason: "更新保留场景根节点的变换，不重建网格。",
              performanceRole: "responsiveness",
              step: 0.01,
              target: "robot.scale",
              type: "slider",
              unit: "×",
            },
            positionX: {
              defaultValue: 0,
              label: "位移 X",
              max: 2,
              min: -2,
              orderRole: "spatial",
              performanceReason: "只更新机器人根节点 X 位置。",
              performanceRole: "responsiveness",
              step: 0.01,
              target: "robot.positionX",
              type: "slider",
            },
            positionY: {
              defaultValue: 0,
              label: "位移 Y",
              max: 2,
              min: -2,
              orderRole: "spatial",
              performanceReason: "只更新机器人根节点 Y 位置。",
              performanceRole: "responsiveness",
              step: 0.01,
              target: "robot.positionY",
              type: "slider",
            },
            positionZ: {
              defaultValue: 0,
              label: "位移 Z",
              max: 2,
              min: -2,
              orderRole: "spatial",
              performanceReason: "只更新机器人根节点 Z 位置。",
              performanceRole: "responsiveness",
              step: 0.01,
              target: "robot.positionZ",
              type: "slider",
            },
            rotationX: {
              defaultValue: 0,
              label: "旋转 X",
              max: 180,
              min: -180,
              orderRole: "spatial",
              performanceReason: "只更新机器人根节点 X 旋转。",
              performanceRole: "responsiveness",
              step: 1,
              target: "robot.rotationX",
              type: "slider",
              unit: "°",
            },
            rotationY: {
              defaultValue: 0,
              label: "旋转 Y",
              max: 180,
              min: -180,
              orderRole: "spatial",
              performanceReason: "只更新机器人根节点 Y 旋转。",
              performanceRole: "responsiveness",
              step: 1,
              target: "robot.rotationY",
              type: "slider",
              unit: "°",
            },
            rotationZ: {
              defaultValue: 0,
              label: "旋转 Z",
              max: 180,
              min: -180,
              orderRole: "spatial",
              performanceReason: "只更新机器人根节点 Z 旋转。",
              performanceRole: "responsiveness",
              step: 1,
              target: "robot.rotationZ",
              type: "slider",
              unit: "°",
            },
          },
        },
        {
          id: "capture-mapping",
          title: "捕捉映射",
          controls: {
            sensitivity: {
              defaultValue: 2,
              description: "放大或缩小摄像头姿态变化；数值越大，机器人响应幅度越大。",
              keyframeable: false,
              label: "整体灵敏度",
              max: 5,
              min: 0.25,
              orderRole: "primary",
              performanceReason: "只改变摄像头角度到关节角度的映射倍率。",
              performanceRole: "responsiveness",
              step: 0.05,
              target: "capture.sensitivity",
              type: "slider",
              unit: "×",
            },
            maxPitch: {
              defaultValue: 45,
              description: "摄像头 Pitch 映射到机器人 Pitch 的最大角度。",
              keyframeable: false,
              label: "Pitch 最大角度",
              max: 180,
              min: 5,
              orderRole: "detail",
              performanceReason: "只限制 axis1 输出角度。",
              performanceRole: "responsiveness",
              step: 1,
              target: "capture.maxPitch",
              type: "slider",
              unit: "°",
            },
            maxRoll: {
              defaultValue: 45,
              description: "摄像头 Roll 映射到机器人 Roll 的最大角度。",
              keyframeable: false,
              label: "Roll 最大角度",
              max: 180,
              min: 5,
              orderRole: "detail",
              performanceReason: "只限制 axis2 输出角度。",
              performanceRole: "responsiveness",
              step: 1,
              target: "capture.maxRoll",
              type: "slider",
              unit: "°",
            },
            maxYaw: {
              defaultValue: 90,
              description: "摄像头 Yaw 映射到机器人 Yaw 的最大角度。",
              keyframeable: false,
              label: "Yaw 最大角度",
              max: 180,
              min: 5,
              orderRole: "detail",
              performanceReason: "只限制 axis3 输出角度。",
              performanceRole: "responsiveness",
              step: 1,
              target: "capture.maxYaw",
              type: "slider",
              unit: "°",
            },
          },
        },
        {
          id: "geometry",
          title: "Link 长度 / Joint Origin Z",
          controls: {
            pitchLength: {
              applicability: { mode: "conditional", all: [{ equals: "head1", target: "model.variant" }] },
              defaultValue: 0.028,
              label: "axis1 → pitch_Link",
              max: 0.2,
              min: 0,
              orderRole: "detail",
              performanceReason: "更新 axis1 原点并重算机器人连杆层级。",
              performanceRole: "responsiveness",
              step: 0.001,
              target: "geometry.axis1OriginZ",
              type: "slider",
              unit: "m",
            },
            rollLength: {
              applicability: { mode: "conditional", all: [{ equals: "head1", target: "model.variant" }] },
              defaultValue: 0.048,
              label: "axis2 → roll_Link",
              max: 0.2,
              min: 0,
              orderRole: "detail",
              performanceReason: "更新 axis2 原点并重算机器人连杆层级。",
              performanceRole: "responsiveness",
              step: 0.001,
              target: "geometry.axis2OriginZ",
              type: "slider",
              unit: "m",
            },
            yawLength: {
              applicability: { mode: "conditional", all: [{ equals: "head1", target: "model.variant" }] },
              defaultValue: 0.082,
              label: "axis3 → yaw_Link",
              max: 0.25,
              min: 0,
              orderRole: "detail",
              performanceReason: "更新 axis3 原点并重算机器人连杆层级。",
              performanceRole: "responsiveness",
              step: 0.001,
              target: "geometry.axis3OriginZ",
              type: "slider",
              unit: "m",
            },
          },
        },
        {
          id: "head2-centers",
          title: "头部旋转中心",
          controls: {
            pitchCenterX: {
              applicability: { mode: "conditional", all: [{ oneOf: ["head2", "head3"], target: "model.variant" }] },
              defaultValue: 0,
              description: "红色标记所示的 头部 Pitch 关节旋转中心。",
              label: "Pitch 中心 X",
              max: 0.2,
              min: -0.2,
              orderRole: "spatial",
              performanceReason: "更新 头部 Pitch 关节旋转中心。",
              performanceRole: "responsiveness",
              semanticGroup: "pitch-center",
              step: 0.001,
              target: "geometry.head2PitchCenterX",
              type: "slider",
              unit: "m",
            },
            pitchCenterY: {
              applicability: { mode: "conditional", all: [{ oneOf: ["head2", "head3"], target: "model.variant" }] },
              defaultValue: 0,
              label: "Pitch 中心 Y",
              max: 0.2,
              min: -0.2,
              orderRole: "spatial",
              performanceReason: "更新 头部 Pitch 关节旋转中心。",
              performanceRole: "responsiveness",
              semanticGroup: "pitch-center",
              step: 0.001,
              target: "geometry.head2PitchCenterY",
              type: "slider",
              unit: "m",
            },
            pitchCenterZ: {
              applicability: { mode: "conditional", all: [{ oneOf: ["head2", "head3"], target: "model.variant" }] },
              defaultValue: 0.081,
              label: "Pitch 中心 Z",
              max: 0.3,
              min: -0.1,
              orderRole: "spatial",
              performanceReason: "更新 头部 Pitch 关节旋转中心。",
              performanceRole: "responsiveness",
              semanticGroup: "pitch-center",
              step: 0.001,
              target: "geometry.head2PitchCenterZ",
              type: "slider",
              unit: "m",
            },
            rollCenterX: {
              applicability: { mode: "conditional", all: [{ oneOf: ["head2", "head3"], target: "model.variant" }] },
              defaultValue: 0,
              description: "绿色标记所示的 头部 Roll 关节旋转中心。",
              label: "Roll 中心 X",
              max: 0.2,
              min: -0.2,
              orderRole: "spatial",
              performanceReason: "更新 头部 Roll 关节旋转中心。",
              performanceRole: "responsiveness",
              semanticGroup: "roll-center",
              step: 0.001,
              target: "geometry.head2RollCenterX",
              type: "slider",
              unit: "m",
            },
            rollCenterY: {
              applicability: { mode: "conditional", all: [{ oneOf: ["head2", "head3"], target: "model.variant" }] },
              defaultValue: 0,
              label: "Roll 中心 Y",
              max: 0.2,
              min: -0.2,
              orderRole: "spatial",
              performanceReason: "更新 头部 Roll 关节旋转中心。",
              performanceRole: "responsiveness",
              semanticGroup: "roll-center",
              step: 0.001,
              target: "geometry.head2RollCenterY",
              type: "slider",
              unit: "m",
            },
            rollCenterZ: {
              applicability: { mode: "conditional", all: [{ oneOf: ["head2", "head3"], target: "model.variant" }] },
              defaultValue: 0,
              label: "Roll 中心 Z",
              max: 0.3,
              min: -0.1,
              orderRole: "spatial",
              performanceReason: "更新 头部 Roll 关节旋转中心。",
              performanceRole: "responsiveness",
              semanticGroup: "roll-center",
              step: 0.001,
              target: "geometry.head2RollCenterZ",
              type: "slider",
              unit: "m",
            },
            yawCenterX: {
              applicability: { mode: "conditional", all: [{ oneOf: ["head2", "head3"], target: "model.variant" }] },
              defaultValue: 0,
              description: "蓝色标记所示的 头部 Yaw 关节旋转中心。",
              label: "Yaw 中心 X",
              max: 0.2,
              min: -0.2,
              orderRole: "spatial",
              performanceReason: "更新 头部 Yaw 关节旋转中心。",
              performanceRole: "responsiveness",
              semanticGroup: "yaw-center",
              step: 0.001,
              target: "geometry.head2YawCenterX",
              type: "slider",
              unit: "m",
            },
            yawCenterY: {
              applicability: { mode: "conditional", all: [{ oneOf: ["head2", "head3"], target: "model.variant" }] },
              defaultValue: 0,
              label: "Yaw 中心 Y",
              max: 0.2,
              min: -0.2,
              orderRole: "spatial",
              performanceReason: "更新 头部 Yaw 关节旋转中心。",
              performanceRole: "responsiveness",
              semanticGroup: "yaw-center",
              step: 0.001,
              target: "geometry.head2YawCenterY",
              type: "slider",
              unit: "m",
            },
            yawCenterZ: {
              applicability: { mode: "conditional", all: [{ oneOf: ["head2", "head3"], target: "model.variant" }] },
              defaultValue: 0.0565,
              label: "Yaw 中心 Z",
              max: 0.3,
              min: -0.1,
              orderRole: "spatial",
              performanceReason: "更新 头部 Yaw 关节旋转中心。",
              performanceRole: "responsiveness",
              semanticGroup: "yaw-center",
              step: 0.001,
              target: "geometry.head2YawCenterZ",
              type: "slider",
              unit: "m",
            },
          },
        },
        {
          id: "limits",
          title: "角度限位",
          controls: {
            pitchLimits: {
              defaultValue: [-0.61, 0.61],
              label: "Pitch 下限 / 上限",
              max: 3.14,
              min: -3.14,
              orderRole: "spatial",
              performanceReason: "更新 axis1 限位并钳制当前姿态。",
              performanceRole: "responsiveness",
              step: 0.01,
              target: "limits.axis1",
              type: "rangeSlider",
              unit: "rad",
            },
            rollLimits: {
              defaultValue: [-0.52, 0.52],
              label: "Roll 下限 / 上限",
              max: 3.14,
              min: -3.14,
              orderRole: "spatial",
              performanceReason: "更新 axis2 限位并钳制当前姿态。",
              performanceRole: "responsiveness",
              step: 0.01,
              target: "limits.axis2",
              type: "rangeSlider",
              unit: "rad",
            },
            yawLimits: {
              defaultValue: [-1.65, 1.65],
              label: "Yaw 下限 / 上限",
              max: 3.14,
              min: -3.14,
              orderRole: "spatial",
              performanceReason: "更新 axis3 限位并钳制当前姿态。",
              performanceRole: "responsiveness",
              step: 0.01,
              target: "limits.axis3",
              type: "rangeSlider",
              unit: "rad",
            },
          },
        },
        {
          id: "view",
          title: "视图",
          controls: {
            distance: {
              defaultValue: 4.5,
              keyframeable: false,
              label: "摄像机距离",
              max: 10,
              min: 2.5,
              orderRole: "detail",
              performanceReason: "只更新摄像机位置。",
              performanceRole: "responsiveness",
              step: 0.1,
              target: "camera.distance",
              type: "slider",
            },
            fov: {
              defaultValue: 36,
              keyframeable: false,
              label: "视场角 FOV",
              max: 75,
              min: 20,
              orderRole: "detail",
              performanceReason: "只更新摄像机投影矩阵。",
              performanceRole: "responsiveness",
              step: 1,
              target: "camera.fov",
              type: "slider",
              unit: "°",
            },
            targetHeight: {
              defaultValue: 0,
              keyframeable: false,
              label: "观察中心高度",
              max: 1.5,
              min: -1.5,
              orderRole: "detail",
              performanceReason: "只更新摄像机观察目标。",
              performanceRole: "responsiveness",
              step: 0.01,
              target: "camera.targetZ",
              type: "slider",
            },
            orientation: {
              defaultValue: { position: [3.4, 2.4, 1.8], up: [0, 0, 1] },
              description: "拖动视图方向球或点击轴点检查机器人头部。",
              keyframeable: false,
              label: false,
              orderRole: "detail",
              performanceReason: "更新相机姿态而不重建 URDF 或网格。",
              performanceRole: "responsiveness",
              target: "view.orbit",
              type: "orientationGizmo",
            },
          },
        },
        {
          id: "image-export",
          title: "Image Export",
          controls: {
            format: {
              defaultValue: "png",
              keyframeable: false,
              label: "Format",
              options: [
                { label: "PNG", value: "png" },
                { label: "JPG", value: "jpg" },
              ],
              orderRole: "mode",
              performanceReason: "选择运行时图像编码器。",
              performanceRole: "responsiveness",
              target: "export.image.format",
              type: "select",
            },
            resolution: {
              defaultValue: "4k",
              keyframeable: false,
              label: "Resolution",
              options: [
                { label: "2K", value: "2k" },
                { label: "4K", value: "4k" },
                { label: "8K", value: "8k" },
              ],
              orderRole: "mode",
              performanceReason: "控制导出像素面积。",
              performanceRole: "workload",
              target: "export.image.resolution",
              type: "select",
            },
          },
          layoutGroups: [{ columns: 2, controls: ["format", "resolution"], layout: "inline" }],
        },
        {
          id: "video-export",
          title: "Video Export",
          controls: {
            format: {
              defaultValue: "mp4",
              keyframeable: false,
              label: "Format",
              options: [
                { label: "MP4", value: "mp4" },
                { label: "WebM", value: "webm" },
              ],
              orderRole: "mode",
              performanceReason: "选择运行时视频容器与编解码器。",
              performanceRole: "responsiveness",
              target: "export.video.format",
              type: "select",
            },
            resolution: {
              defaultValue: "current",
              keyframeable: false,
              label: "Resolution",
              options: [
                { label: "Current", value: "current" },
                { label: "4K", value: "4k" },
              ],
              orderRole: "mode",
              performanceReason: "控制离线逐帧视频编码的像素面积。",
              performanceRole: "workload",
              target: "export.video.resolution",
              type: "select",
            },
            rotationCenters: {
              applicability: { mode: "always" },
              defaultValue: false,
              description: "导出 MP4、WebM 或 GIF 时叠加当前三轴旋转中心标记。",
              keyframeable: false,
              label: "显示旋转中心",
              orderRole: "detail",
              performanceReason: "只切换导出帧中的三组轻量 Three.js 标记。",
              performanceRole: "responsiveness",
              target: "export.video.includeRotationCenters",
              type: "switch",
            },
          },
          layoutGroups: [{ columns: 2, controls: ["format", "resolution"], layout: "inline" }],
        },
        {
          actionGroup: "primary",
          id: "export",
          title: "Export",
          controls: {
            output: {
              actions: [
                { icon: "export", label: "Export Image", role: "export-image", value: "export.image" },
                { icon: "export", label: "Export Video", role: "export-video", value: "export.video" },
                { icon: "download", label: "Export GIF", role: "download-output", value: "export.gif" },
              ],
              defaultValue: null,
              keyframeable: false,
              label: false,
              orderRole: "action",
              target: "actions.export",
              type: "panelActions",
            },
          },
        },
      ],
      title: "机器人头部控制",
    },
    timeline: { defaultDurationSeconds: 4, enabled: true, mode: "keyframes" },
  },
  persistence: {
    additionalValueTargets: ["source.urdfFolder", "capture.headTracking", "capture.sensitivity", "capture.maxPitch", "capture.maxRoll", "capture.maxYaw"],
    include: ["values", "canvas", "panels", "timeline"],
    key: "toolcraft:robot-head-studio:state:v1",
    storage: "localStorage",
    version: 1,
  },
  settingsTransfer: "auto",
  toolbar: {
    history: true,
    radar: true,
    theme: true,
    zoom: true,
  },
});
